-- Add Foreign Key and Check Constraints.

ALTER TABLE "AIRPLANE" ADD CONSTRAINT "AIRPLANE_MODEL" FOREIGN KEY ("MODEL_ID")
	  REFERENCES "MODEL" ("MODEL_ID") ENABLE;

ALTER TABLE "BOOKING" ADD CONSTRAINT "BOOKED" FOREIGN KEY ("CUST_ID")
	  REFERENCES "CUSTOMER" ("CUST_ID") ENABLE;
 
ALTER TABLE "BOOKING" ADD CONSTRAINT "BOOKING_TICKET" FOREIGN KEY ("TICKET_ID")
	  REFERENCES "TICKET" ("TICKET_ID") ENABLE;

ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUST_ACCT" FOREIGN KEY ("ACCT_ID")
	  REFERENCES "C_ACCT" ("ACCT_ID") ENABLE;

ALTER TABLE "LEG" ADD CONSTRAINT "LEG_AIRPLANE" FOREIGN KEY ("AIRPLANE_ID")
	  REFERENCES "AIRPLANE" ("AIRPLANE_ID") ENABLE;
 
ALTER TABLE "LEG" ADD CONSTRAINT "CAPTAIN" FOREIGN KEY ("CAPTAIN_ID")
	  REFERENCES "PILOT" ("PILOT_ID") ENABLE;
 
ALTER TABLE "LEG" ADD CONSTRAINT "COPILOT" FOREIGN KEY ("COPILOT_ID")
	  REFERENCES "PILOT" ("PILOT_ID") ENABLE;
 
ALTER TABLE "LEG" ADD CONSTRAINT "LEG_FLIGHT" FOREIGN KEY ("FLIGHT_ID")
	  REFERENCES "FLIGHT" ("FLIGHT_ID") ENABLE;
 
ALTER TABLE "LEG" ADD CONSTRAINT "LEG_ROUTE" FOREIGN KEY ("ROUTE_ID")
	  REFERENCES "ROUTE" ("ROUTE_ID") ENABLE;
    
ALTER TABLE "MANAGER" ADD CONSTRAINT "MAN_ACCT" FOREIGN KEY ("ACCT_ID")
	  REFERENCES "E_ACCT" ("ACCT_ID") ENABLE;

ALTER TABLE "ROUTE" ADD CONSTRAINT "ARRIVING" FOREIGN KEY ("ARRI_AP_ID")
	  REFERENCES "AIRPORT" ("AIRPORT_ID") ENABLE;
 
ALTER TABLE "ROUTE" ADD CONSTRAINT "DEPARTING" FOREIGN KEY ("DEPT_AP_ID")
	  REFERENCES "AIRPORT" ("AIRPORT_ID") ENABLE;

ALTER TABLE "PILOT" ADD CONSTRAINT "PILOT_ACCT" FOREIGN KEY ("ACCT_ID")
	  REFERENCES "E_ACCT" ("ACCT_ID") ENABLE;
    
ALTER TABLE "TICKET" ADD CONSTRAINT "TICKET_LEG" FOREIGN KEY ("LEG_ID")
	  REFERENCES "LEG" ("LEG_ID") ENABLE;

ALTER TABLE "CREDIT_CARD" ADD CONSTRAINT "CC_CUST" FOREIGN KEY ("CUST_ID")
	  REFERENCES "CUSTOMER" ("CUST_ID") ENABLE;