CREATE TABLE "AIRPLANE" (	
    "AIRPLANE_ID" NUMBER NOT NULL, 
    "CALL_SIGN" VARCHAR2(20 BYTE) NOT NULL, 
    "MODEL_ID" NUMBER NOT NULL, 
    "FUEL" NUMBER NOT NULL, 
    "PAYLOAD" NUMBER NOT NULL, 
    "FLIGHT_HRS" NUMBER NOT NULL, 
    "SERVICE_SINCE" DATE NOT NULL,
    
    CONSTRAINT "AIRPLANE_PK" PRIMARY KEY ("AIRPLANE_ID")
);

CREATE TABLE "AIRPORT" (
  "AIRPORT_ID" NUMBER NOT NULL, 
  "IATA_FAA" VARCHAR2(3 BYTE) NOT NULL,  
	"ICAO" VARCHAR2(4 BYTE), 
  "NAME" VARCHAR2(20 BYTE) NOT NULL,
	"CITY" VARCHAR2(20 BYTE) NOT NULL, 
	"COUNTRY" VARCHAR2(20 BYTE) NOT NULL, 
	"LATITUDE" NUMBER NOT NULL, 
	"LONGITUDE" NUMBER NOT NULL, 
	"ALTITUDE" NUMBER NOT NULL, 
	"TIME_ZONE" NUMBER NOT NULL, 
	"DST" VARCHAR2(2 BYTE) NOT NULL,
  
  CONSTRAINT "AIRPORT_PK" PRIMARY KEY ("AIRPORT_ID")
);


CREATE TABLE "BOOKING" (
  "BOOKING_ID" NUMBER NOT NULL, 
	"PRICE" NUMBER NOT NULL, 
	"FF_MILES" NUMBER NOT NULL, 
	"BAGS" NUMBER NOT NULL, 
	"TICKET_ID" NUMBER NOT NULL, 
	"CUST_ID" NUMBER NOT NULL,
  
  CONSTRAINT "BOOKING_PK" PRIMARY KEY ("BOOKING_ID")
);

    
CREATE TABLE "C_ACCT" (
  "ACCT_ID" NUMBER NOT NULL, 
	"USERNAME" VARCHAR2(20 BYTE) NOT NULL, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL,
  
  CONSTRAINT "C_ACCT_PK" PRIMARY KEY ("ACCT_ID")
);


CREATE TABLE "CREDIT_CARD" (
  "CC_ID" NUMBER NOT NULL,
  "CCN" NUMBER NOT NULL,
  "NAME" VARCHAR(20 BYTE) NOT NULL,
  "EXPIRES" DATE NOT NULL,
  "CUST_ID" NUMBER NOT NULL,
  
  CONSTRAINT "CREDIT_CARD_PK" PRIMARY KEY ("CC_ID")
);


CREATE TABLE "CUSTOMER" (
  "CUST_ID" NUMBER NOT NULL, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL, 
	"ACCT_ID" NUMBER NOT NULL, 
	"FF_MILES" NUMBER NOT NULL,
  
  CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUST_ID")
);

CREATE TABLE "E_ACCT" (
  "ACCT_ID" NUMBER NOT NULL, 
	"USERNAME" VARCHAR2(20 BYTE) NOT NULL, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL,
  
  CONSTRAINT "E_ACCT_PK" PRIMARY KEY ("ACCT_ID")
);


CREATE TABLE "FLIGHT" (
  "FLIGHT_ID" NUMBER NOT NULL,
  "FLIGHT_NUM" NUMBER NOT NULL, 
  "STATUS" VARCHAR(20 BYTE) NOT NULL,
  "DELAY" NUMBER NOT NULL,
  
  CONSTRAINT "FLIGHT_PK" PRIMARY KEY ("FLIGHT_ID")
);



CREATE TABLE "LEG" (
  "LEG_ID" NUMBER NOT NULL,
  "ARR_TIME" DATE NOT NULL, 
	"DEP_TIME" DATE NOT NULL,
  
	"ROUTE_ID" NUMBER NOT NULL, 
  "FLIGHT_ID" NUMBER NOT NULL, 
	"CAPTAIN_ID" NUMBER NOT NULL, 
	"COPILOT_ID" NUMBER, 
	"AIRPLANE_ID" NUMBER NOT NULL,
  
  CONSTRAINT "LEG_PK" PRIMARY KEY ("LEG_ID")
);

CREATE TABLE "MANAGER" (
  "MANAGER_ID" NUMBER NOT NULL, 
	"EMP_ID" VARCHAR(20 BYTE) NOT NULL, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL, 
	"SALARY" NUMBER NOT NULL, 
	"POSITION" VARCHAR2(20 BYTE) NOT NULL, 
	"ACCT_ID" NUMBER NOT NULL,
  
  CONSTRAINT "MANAGER_PK" PRIMARY KEY ("MANAGER_ID")
);


CREATE TABLE "MODEL" (
  "MODEL_ID" NUMBER NOT NULL, 
	"MAKE" VARCHAR2(20 BYTE) NOT NULL, 
	"MODEL" VARCHAR2(20 BYTE) NOT NULL, 
	"PAYLOAD" NUMBER NOT NULL, 
	"SEATS" NUMBER NOT NULL, 
	"SEAT_ROWS" NUMBER NOT NULL, 
	"SEAT_COLS" NUMBER NOT NULL, 
	"MAX_FUEL" NUMBER NOT NULL, 
	"WEIGHT" NUMBER NOT NULL, 
	"RANGE" NUMBER NOT NULL, 
	"MAX_SPEED" NUMBER NOT NULL,
  
  CONSTRAINT "MODEL_PK" PRIMARY KEY ("MODEL_ID")
);
  

CREATE TABLE "PILOT" (
  "PILOT_ID" NUMBER NOT NULL,
  "EMP_ID" VARCHAR(20 BYTE) NOT NULL,
	"NAME" VARCHAR2(20 BYTE) NOT NULL, 
	"SALARY" NUMBER NOT NULL, 
	"AGE" NUMBER NOT NULL,
  "FLIGHT_HOURS" NUMBER NOT NULL,
  "ACCT_ID" NUMBER NOT NULL,
  
  CONSTRAINT "PILOT_PK" PRIMARY KEY ("PILOT_ID")
   );

CREATE TABLE "ROUTE" (
  "ROUTE_ID" NUMBER NOT NULL, 
	"DEPT_AP_ID" NUMBER NOT NULL, 
	"ARRI_AP_ID" NUMBER NOT NULL, 
	"DISTANCE" NUMBER NOT NULL,
  CONSTRAINT "ROUTE_PK" PRIMARY KEY ("ROUTE_ID")
   );


CREATE TABLE "TICKET" (
  "TICKET_ID" NUMBER NOT NULL, 
	"SEAT" VARCHAR2(20 BYTE) NOT NULL, 
	"BOARDING_GROUP" VARCHAR2(20 BYTE) NOT NULL, 
	"CLASS" VARCHAR2(20 BYTE) NOT NULL, 
	"LEG_ID" NUMBER NOT NULL,
  CONSTRAINT "TICKET_PK" PRIMARY KEY ("TICKET_ID")
);
