
CREATE OR REPLACE TRIGGER "KDR213"."AIRPLANE_ID_SEQ_TRIGGER" 
BEFORE INSERT ON AIRPLANE 
REFERENCING NEW AS newa
FOR EACH ROW 
BEGIN
  SELECT AIRPLANE_ID_SEQ.nextval
        INTO :newa.AIRPLANE_ID
        FROM dual;

END;
/
ALTER TRIGGER "KDR213"."AIRPLANE_ID_SEQ_TRIGGER" ENABLE;



CREATE OR REPLACE TRIGGER "KDR213"."BOOKING_ID_SEQ_TRIGGER" 
BEFORE INSERT ON BOOKING 
REFERENCING NEW AS newa
FOR EACH ROW 
BEGIN
  SELECT BOOKING_ID_SEQ.nextval
        INTO :newa.BOOKING_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."BOOKING_ID_SEQ_TRIGGER" ENABLE;


CREATE OR REPLACE TRIGGER "KDR213"."C_ACCT_ID_SEQ_TRIGGER" 
BEFORE INSERT ON C_ACCT 
REFERENCING NEW AS newa
FOR EACH ROW 
BEGIN
  SELECT C_ACCT_ID_SEQ.nextval
        INTO :newa.ACCT_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."C_ACCT_ID_SEQ_TRIGGER" ENABLE;



CREATE OR REPLACE TRIGGER "KDR213"."CUST_ID_SEQ_TRIGGER" 
BEFORE INSERT ON CUSTOMER
REFERENCING NEW AS newa
FOR EACH ROW 
BEGIN
  SELECT CUST_ID_SEQ.nextval
        INTO :newa.CUST_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."CUST_ID_SEQ_TRIGGER" ENABLE;



CREATE OR REPLACE TRIGGER "KDR213"."E_ACCT_ID_SEQ_TRIGGER" 
BEFORE INSERT ON E_ACCT 
REFERENCING NEW AS newa
FOR EACH ROW 
BEGIN
  SELECT E_ACCT_ID_SEQ.nextval
        INTO :newa.ACCT_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."E_ACCT_ID_SEQ_TRIGGER" ENABLE;



CREATE OR REPLACE TRIGGER "KDR213"."FLIGHT_ID_SEQ_TRIGGER" 
BEFORE INSERT ON FLIGHT 
REFERENCING NEW AS newa
FOR EACH ROW 
BEGIN
  SELECT FLIGHT_ID_SEQ.nextval
        INTO :newa.FLIGHT_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."FLIGHT_ID_SEQ_TRIGGER" ENABLE;


CREATE OR REPLACE TRIGGER "KDR213"."LEG_ID_SEQ_TRIGGER" 
BEFORE INSERT ON LEG 
REFERENCING NEW AS newa
FOR EACH ROW
BEGIN
  SELECT LEG_ID_SEQ.nextval
        INTO :newa.LEG_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."LEG_ID_SEQ_TRIGGER" ENABLE;



CREATE OR REPLACE TRIGGER "KDR213"."MODEL_ID_SEQ_TRIGGER" 
BEFORE INSERT ON MODEL 
REFERENCING NEW AS newa
FOR EACH ROW
BEGIN
  SELECT MODEL_ID_SEQ.nextval
        INTO :newa.MODEL_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."MODEL_ID_SEQ_TRIGGER" ENABLE;


CREATE OR REPLACE TRIGGER "KDR213"."PILOT_ID_SEQ_TRIGGER" 
BEFORE INSERT ON PILOT 
REFERENCING NEW AS newa
FOR EACH ROW
BEGIN
  SELECT PILOT_ID_SEQ.nextval
        INTO :newa.PILOT_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."PILOT_ID_SEQ_TRIGGER" ENABLE;



CREATE OR REPLACE TRIGGER "KDR213"."ROUTE_ID_SEQ_TRIGGER" 
BEFORE INSERT ON ROUTE 
REFERENCING NEW AS newa
FOR EACH ROW
BEGIN
  SELECT ROUTE_ID_SEQ.nextval
        INTO :newa.ROUTE_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."ROUTE_ID_SEQ_TRIGGER" ENABLE;


CREATE OR REPLACE TRIGGER "KDR213"."TICKET_ID_SEQ_TRIGGER" 
BEFORE INSERT ON TICKET 
REFERENCING NEW AS newa
FOR EACH ROW
BEGIN
  SELECT TICKET_ID_SEQ.nextval
        INTO :newa.TICKET_ID
        FROM dual;
END;
/
ALTER TRIGGER "KDR213"."TICKET_ID_SEQ_TRIGGER" ENABLE;


CREATE OR REPLACE TRIGGER "KDR213"."MANAGER_ID_SEQ_TRIGGER" 
BEFORE INSERT ON MANAGER 
REFERENCING NEW AS newa
FOR EACH ROW
BEGIN
  SELECT MANAGER_ID_SEQ.nextval
        INTO :newa.MANAGER_ID
        FROM dual;

END;
/
ALTER TRIGGER "KDR213"."MANAGER_ID_SEQ_TRIGGER" ENABLE;


CREATE OR REPLACE TRIGGER "KDR213"."MANAGER_EMP_ID_SEQ_TRIGGER" 
BEFORE INSERT ON MANAGER 
REFERENCING NEW AS newa
FOR EACH ROW
BEGIN
  SELECT CONCAT(EMP_ID_SEQ.nextval,'M')
        INTO :newa.EMP_ID
        FROM dual;

END;
/
ALTER TRIGGER "KDR213"."PILOT_EMP_ID_SEQ_TRIGGER" ENABLE;


CREATE OR REPLACE TRIGGER "KDR213"."PILOT_EMP_ID_SEQ_TRIGGER" 
BEFORE INSERT ON MANAGER 
REFERENCING NEW AS newa
FOR EACH ROW
BEGIN
  SELECT CONCAT(EMP_ID_SEQ.nextval,'P')
        INTO :newa.EMP_ID
        FROM dual;

END;
/
ALTER TRIGGER "KDR213"."PILOT_EMP_ID_SEQ_TRIGGER" ENABLE;




